# yamllint disable rule:line-length
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observiq-node
  namespace: data-preparation
spec:
  mode: daemonset
  hostNetwork: true
  config: |
    receivers:
      plugin/kubelet:
        path: /etc/otel/plugins/kubelet_logs.yaml
        parameters:
          journald_directory: /var/log/journal
          start_at: end

      plugin/container:
        path: /etc/otel/plugins/container_logs.yaml
        parameters:
          start_at: end

      kubeletstats:
        auth_type: serviceAccount
        collection_interval: 60s
        insecure_skip_verify: true
        k8s_api_config:
          auth_type: serviceAccount
        metric_groups:
        - node
        - pod
        - container

    processors:
      k8sattributes:
        auth_type: serviceAccount
        passthrough: false
        pod_association:
        - from: resource_attribute
          name: k8s.pod.uid
        - from: resource_attribute
          name: k8s.pod.name
        filter:
            node_from_env_var: ${KUBE_NODE_NAME}

      resource:
        attributes:
        - key: k8s.cluster.name
          value: "${K8S_CLUSTER}"
          action: upsert

      batch:
        send_batch_max_size: 1000
        send_batch_size: 1000
        timeout: 2s

    exporters:
      otlp:
        endpoint: observiq-gateway:4317
        tls:
          insecure: true

    extensions:
      file_storage:
        directory: /var/lib/observiq/otelcol/node

    service:
      extensions:
        - file_storage
      pipelines:
        metrics:
          receivers:
            - kubeletstats
          processors:
            - k8sattributes
            - resource
            - batch
          exporters:
            - otlp
        logs:
          receivers:
            - plugin/kubelet
            - plugin/container
          processors:
            - k8sattributes
            - resource
            - batch
          exporters:
            - otlp

  image: observiq/observiq-otel-collector:1.9.0
  serviceAccount: observiq-otel-collector
  resources:
    requests:
      memory: 250Mi
      cpu: 250m
  volumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: dockerlogs
      hostPath:
        path: /var/lib/docker/containers
    - name: storage
      hostPath:
        path: /var/lib/observiq/otelcol/node
  volumeMounts:
    - mountPath: /var/log
      name: varlog
    - mountPath: /var/lib/docker/containers
      name: dockerlogs
    - mountPath: /var/lib/observiq/otelcol/node
      name: storage
      readOnly: false
  podSecurityContext:
    runAsUser: 0
